# =========================================================================
# eWAF ModSecurity Main Configuration Bridge
# =========================================================================

# 1. Cargar el motor base y todas las reglas oficiales del OWASP CRS 
# (Ruta interna absoluta revelada por el contenedor)
Include /etc/nginx/modsecurity.d/setup.conf

# 2. Cargar nuestras configuraciones personalizadas y excepciones de eWAF
Include /etc/modsecurity.d/modsecurity-custom.conf